//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SstDCSA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_users
    {
        public int user_id { get; set; }
        [Display(Name = "User Name ")]
        public string user_name { get; set; }
        [Display(Name = "User Password ")]
        public string user_password { get; set; }
        [Display(Name = "User Role ")]
        public string user_role { get; set; }
        [Display(Name = "Center Code ")]
        public Nullable<int> user_center_code { get; set; }
    
        public virtual tbl_center tbl_center { get; set; }
    }
}
