//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SstDCSA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_DCSA3304_mark3
    {
        public int id { get; set; }
        [Display(Name = "Student ID ")]
        public string st_registration { get; set; }
        [Display(Name = "Course Code ")]
        public string subj_code { get; set; }
        [Display(Name = "Real Life Project Report Mark ")]
        [Range(0, 80)]
        public Nullable<int> project_report { get; set; }
        [Display(Name = "Viva Mark ")]
        [Range(0, 20)]
        public Nullable<int> viva { get; set; }
        [Display(Name = "Center Code ")]
        public Nullable<int> st_center_code { get; set; }
        [Display(Name = "Submit Date ")]
        public Nullable<System.DateTime> submit_date { get; set; }
        [Display(Name = "Exam Term ")]
        public Nullable<int> exam_term { get; set; }
    
        public virtual tbl_student tbl_student { get; set; }
    }
}
