//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SstDCSA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_student()
        {
            this.tbl_DCSA1201_mark1 = new HashSet<tbl_DCSA1201_mark1>();
            this.tbl_DCSA1302_mark1 = new HashSet<tbl_DCSA1302_mark1>();
            this.tbl_DCSA1303_mark1 = new HashSet<tbl_DCSA1303_mark1>();
            this.tbl_DCSA1304_mark1 = new HashSet<tbl_DCSA1304_mark1>();
            this.tbl_DCSA2301_mark2 = new HashSet<tbl_DCSA2301_mark2>();
            this.tbl_DCSA2302_mark2 = new HashSet<tbl_DCSA2302_mark2>();
            this.tbl_DCSA2303_mark2 = new HashSet<tbl_DCSA2303_mark2>();
            this.tbl_DCSA2304_mark2 = new HashSet<tbl_DCSA2304_mark2>();
            this.tbl_DCSA3301_mark3 = new HashSet<tbl_DCSA3301_mark3>();
            this.tbl_DCSA3302_mark3 = new HashSet<tbl_DCSA3302_mark3>();
            this.tbl_DCSA3303_mark3 = new HashSet<tbl_DCSA3303_mark3>();
            this.tbl_DCSA3304_mark3 = new HashSet<tbl_DCSA3304_mark3>();
        }

        [Display(Name = "Student ID ")]
        public string st_registration { get; set; }
        [Display(Name = "Student Name ")]
        public string st_name { get; set; }
        [Display(Name = "Admission Year ")]
        public Nullable<System.DateTime> st_admission_year { get; set; }
        [Display(Name = "First Semester ")]
        public Nullable<bool> st_semester1 { get; set; }
        [Display(Name = "Second Semester ")]
        public Nullable<bool> st_semester2 { get; set; }
        [Display(Name = "Third Semester ")]
        public Nullable<bool> st_semester3 { get; set; }
        [Display(Name = "Center Code ")]
        public Nullable<int> st_center_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA1201_mark1> tbl_DCSA1201_mark1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA1302_mark1> tbl_DCSA1302_mark1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA1303_mark1> tbl_DCSA1303_mark1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA1304_mark1> tbl_DCSA1304_mark1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA2301_mark2> tbl_DCSA2301_mark2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA2302_mark2> tbl_DCSA2302_mark2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA2303_mark2> tbl_DCSA2303_mark2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA2304_mark2> tbl_DCSA2304_mark2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA3301_mark3> tbl_DCSA3301_mark3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA3302_mark3> tbl_DCSA3302_mark3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA3303_mark3> tbl_DCSA3303_mark3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DCSA3304_mark3> tbl_DCSA3304_mark3 { get; set; }
    }
}
